"$schema" = 'https://starship.rs/config-schema.json'
# Based on gruvbox material and tyriansnow themes
format = """
[](color_purple)\
$os\
$username\
[](bg:color_blue fg:color_purple)\
$directory\
[](fg:color_blue bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_green)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_green bg:color_yellow)\
$docker_context\
$conda\
$pixi\
$memory_usage\
[](fg:color_yellow bg:color_orange)\
$time\
[ ](fg:color_orange)\
$line_break$character"""

palette = 'tyriansnow'

[palettes.tyriansnow]
color_bg1 = '#292D3E'
color_bg3 = '#34324a'
color_purple = '#c792ea'
color_blue = '#82aaff'
color_aqua = '#80cbc4'
color_green = '#c3e88d'
color_yellow = '#ffcb6b'
color_orange = '#f78c6c'
color_red = '#f07178'
color_text =  '#eeffff'
color_background = '#282C3D'

[os]
disabled = false
style = "bg:color_purple fg:color_text"

[os.symbols]
Windows = "󰍲"
Linux = "󰌽"
Arch = "󰣇"

[username]
show_always = true
style_user = "bg:color_purple fg:color_text"
style_root = "bg:color_purple fg:color_text"
aliases = { daniel = 'Daniël'}
format = '[ $user ]($style)'

[directory]
style = "fg:color_text bg:color_blue"
format = "[ $path ]($style)"
home_symbol = " "
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"Projects" = "󰏗 "
#  TODO: Add more substitutions

# Git metrics
[git_branch]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol $branch ($remote_name) ](fg:color_text bg:color_aqua)]($style)'

[git_status]
style = "bg:color_green"
format = '[[($all_status$ahead_behind )](fg:color_text bg:color_aqua)]($style)'
# TODO: Expand
[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text bg:color_blue)]($style)'

[cpp]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text bg:color_blue)]($style)'

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_yellow"
format = '[[ $symbol( $context) ](fg:#color_text bg:color_yellow)]($style)'

[conda]
style = "bg:color_yellow"
format = '[[ $symbol( $environment) ](fg:color_text bg:color_yellow)]($style)'

[pixi]
style = "bg:color_yellow"
format = '[[ $symbol( $version)( $environment) ](fg:color_text bg:color_yellow)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_orange"
format = '[[  $time ](fg:color_text bg:color_orange)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
